### ISSUE TITLE
Crash error in noise-box-reaper.js

### ISSUE THREAD

**Issue by jedrichards** [MadeByLoosers/noise-box#47]
```
/var/node/noise-box/app/app/lib/noise-box-reaper.js:9
        model.noiseBoxes.each(function (noiseBox) {
             ^
TypeError: Cannot read property 'noiseBoxes' of undefined
    at Timer.module.exports (/var/node/noise-box/app/app/lib/noise-box-reaper.js:9:14)
    at Timer.exports.setInterval.timer.ontimeout (timers.js:234:14)
```

**Comment by jedrichards** [comment]
Fixed on dev in d489d1e8a3942744309eac4abb84e09c98273a69.
